### ISSUE TITLE
Copyright header in each file

### ISSUE THREAD

**Issue by shiozaki** [BTAS/BTAS#47]
We need one. GPLv3? Please vote. Who owns the copyright (each developer)?

BAGEL embeds BTAS in it at this moment, and I feel uncomfortable doing so without appropriate headers.

**Comment by mbanck** [comment]
This seems still unresolved, only btas/range_iterator.h sems to have a copyright header (likely because it was copied from TiledArray?).

Right now, BTAS cannot be used in any way by other projects, so maybe a stop-gap measure would be to set it to GPLv3 for now, and decide on a more permissive license later.

**Comment by justusc** [comment]
I think range.h and range_iterator were copied from TA. As VT holds the copyright, I think we can give permission to  use those files with a different license.

**Comment by justusc** [comment]
I vote for any permissive license other than LGPL. BSD, MIT, and Boost are all good.

**Comment by shiozaki** [comment]
no preference.

**Comment by mbanck** [comment]
So to summarize: everybody who weighed in said they'd be fine with BSD, or had no preference (some mentioned additional options like MIT or Boost).

BSD is a bit awkward because it encodes the copyright holder in the license text, but http://opensource.org/licenses/BSD-3-Clause has a generic version with "COPYRIGHT HOLDERS AND CONTRIBUTORS".

**Comment by mbanck** [comment]
Could at least a top-level license be mentioned, e.g. in `README.md` or a dedicated `LICENSE.md`? Right now the licensing information seems undefined (unless I am missing something?) which means "default copyright" which means "all rights reserverd", which in theory means using BTAS in downstream open source projects makes it impossible to distribute them legally right now.
